spring:
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
        port: ${server.port}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/spark-dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    name: spark-dev
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 30000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
  boot:
    admin:
      client:
        url: http://127.0.0.1:9002
        instance:
          prefer-ip: true
          service-url: http://${spring.cloud.nacos.discovery.ip}:${spring.cloud.nacos.discovery.port}
        username: spark
        password: spark
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    database: 0
    password:
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: -1
        min-idle: 20
      shutdown-timeout: 10000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
tx-lcn:
  manager:
    host: 127.0.0.1
    port: 8070
    admin-key: 123456
  logger:
    enabled: true
logging:
  level:
    com:
      codingapi:
        txlcn: debug